{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/TRL_RH_SnorkelApp/Pages/TRL_Snorkel_CAP_SRV_QC_ITEM/QC_ITEM_CreateATTACHMENTS.page",
    "_Type": "Action.Type.Navigation"
}