{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "Nav2Sheet2"
	},
	"PageToOpen": "/TRL_RH_SnorkelApp/Pages/SnorkelInstallation2.page",
	"BackStackVisible": true,
	"ClearHistory": false
}