{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "NavToSnorkelInstallationForm"
	},
	"PageToOpen": "/TRL_RH_SnorkelApp/Pages/SnorkelInstallation.page",
	"NavigationType": "Inner",
	"ClientData": {
    "snorkelNo": "{Property:SNORKEL_NO}"
  }
}