{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section111TestCreate3"
	},
	"OnFailure": "/TRL_RH_SnorkelApp/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/TRL_RH_SnorkelApp/Actions/CreateEntitySuccessMessage.action",
	"Target": {
		"Service": "/TRL_RH_SnorkelApp/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"actualvalue": "#Page:SnorkelInstallation3/#Control:Section111TestActualValue2/#Value",
		"date": "#Page:SnorkelInstallation3/#Control:Section111TestDate2/#Value",
		"method": "#Page:SnorkelInstallation3/#Control:Section111TestMethod2/#Value",
		"specification": "#Page:SnorkelInstallation3/#Control:Section111TestSpecification2/#Value",
		"testname": "*6 MOR test result",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}