{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section162Test2CreateD"
	},
	"Target": {
		"Service": "/TRL_RH_SnorkelApp/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"actualvalue": "#Page:SnorkelInstallation/#Control:Section162TestActualGapD/#Value",
		"method": "#Page:SnorkelInstallation/#Control:Section162TestMethodD/#Value",
		"position": "#Page:SnorkelInstallation/#Control:Section162TestPositionGapD/#Value",
		"tolerance": "#Page:SnorkelInstallation/#Control:Section162TestToleranceD/#Value",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}