{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section61Create"
	},
	"OnFailure": "/TRL_RH_SnorkelApp/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/TRL_RH_SnorkelApp/Rules/Section62Visible.js",
	"Target": {
		"Service": "/TRL_RH_SnorkelApp/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation/#Control:Section61Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation/#Control:Section61DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation/#Control:Section61InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation/#Control:Section61Method/#Value",
		"QUESTION": "6.1 height of steel mesh  (750mm +5, -10mm)",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}