{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section151TestCreateC"
	},
	"Target": {
		"Service": "/TRL_RH_SnorkelApp/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_Test_Table"
	},
	"Properties": {
		"ff1": "#Page:SnorkelInstallation5/#Control:Section151FF1/#Value",
		"ff2": "#Page:SnorkelInstallation5/#Control:Section151FF12/#Value",
		"remark": "#Page:SnorkelInstallation5/#Control:Section151TestRemark1/#Value",
		"settleduration": "#Page:SnorkelInstallation5/#Control:Section151SettingTime1/#Value",
		"testname": "*9 Inspection result of outer castable workablity",
		"tf1": "#Page:SnorkelInstallation5/#Control:Section151TF1/#Value",
		"tf2": "#Page:SnorkelInstallation5/#Control:Section151TF12/#Value",
		"watercasting": "#Page:SnorkelInstallation5/#Control:Section151TestWaterCasteing1/#Value",
		"batchNo": "#Page:SnorkelInstallation5/#Control:Section151TestBatchNo1/#Value",
		
		"QUESTION": "15.1 Confirmation of the workability for gap filling castable 'HC-H111B' *9",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}