{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section146Create"
	},
	"OnFailure": "/TRL_RH_SnorkelApp/Actions/CreateEntityFailureMessage.action",
	"Target": {
		"Service": "/TRL_RH_SnorkelApp/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation/#Control:Section146Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation/#Control:Section146DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation/#Control:Section146InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation/#Control:Section146Method/#Value",
		"QUESTION": "14.6 Put Adhesive in alternate bricks and fixing the ring",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}