{
	"_Type": "Action.Type.ODataService.CreateEntity",
	"ActionResult": {
		"_Name": "Section83Create"
	},
	"OnFailure": "/TRL_RH_SnorkelApp/Actions/CreateEntityFailureMessage.action",
	"OnSuccess": "/TRL_RH_SnorkelApp/Rules/Section84Visible.js",
	"Target": {
		"Service": "/TRL_RH_SnorkelApp/Services/TRL_Snorkel_CAP_SRV.service",
		"EntitySet": "QC_ITEM"
	},
	"Properties": {
		"DATE_INSPECTED": "#Page:SnorkelInstallation2/#Control:Section83Date/#Value",
		"DECISION_TAKEN": "#Page:SnorkelInstallation2/#Control:Section83DecisionTaken/#SelectedValue",
		"INSPECTED_BY": "#Page:SnorkelInstallation2/#Control:Section83InspectedBy/#SelectedValue",
		"METHOD": "#Page:SnorkelInstallation2/#Control:Section83Method/#Value",
		"QUESTION": "8.3 Center position",
		"qC_HEADER_SNORKEL_NO": "#Page:SnorkelInstallation/#Control:SnorkelNo/#Value"
	}
}