{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/TRL_RH_SnorkelApp/Pages/TRL_Snorkel_CAP_SRV_ATTACHMENTS/ATTACHMENTS_Create.page",
    "_Type": "Action.Type.Navigation"
}